### ISSUE TITLE
Login page displayed if user goes to start page (IP:4200) being logged-in

### ISSUE THREAD

**Issue by iSomdeb** [engineerscraft/hrms#12]
When user is logged-in, but tries to access the start page (http://<IP>:4200), then the login page is displayed as the root ('') path is mapped to login component.

But if user is already logged-in then we should not display the login page and take him/her to home page.

**Comment by saptarshibasu** [comment]
Done. Changes made in the logincomponent. If the access token is present in the html storage, the user will be redirected to the home page
