### ISSUE TITLE
Field titles are getting overwrite by field values in employee creation page.

### ISSUE THREAD

**Issue by debleena-123** [engineerscraft/hrms#14]
![capture](https://user-images.githubusercontent.com/30408705/28750452-026da51a-7509-11e7-9e00-0468f328749b.PNG)

**Comment by iamjyotirmoy** [comment]
Can you please mention the browser and version being used?

**Comment by debleena-123** [comment]
Version - IE 11 OS-Windows 10

**Comment by saptarshibasu** [comment]
It seems IE & Firefox doesn't support the :placeholder-shown CSS selector yet. So, my change on Friday, breaks this. Let me see, if there is an alternative

**Comment by saptarshibasu** [comment]
Fixed. CSS fix reverted as the new fix is not supported by IE
