### ISSUE TITLE
Employee Hierachy search for newly created employee

### ISSUE THREAD

**Issue by lookatchandra** [engineerscraft/hrms#16]
1.Created new employee with user TEST/TEST.
2.Search the newly created employee in Employee hierarchy search with first name and employee id.

Employee details is not coming.

![emp_hierarchy_search1](https://user-images.githubusercontent.com/29258390/28753007-41afb632-74e1-11e7-9054-841a807817a8.PNG)

![emp_hierachy_search3](https://user-images.githubusercontent.com/29258390/28753009-5550b60a-74e1-11e7-9f06-735465f93400.PNG)

![emp_hierachy_search2](https://user-images.githubusercontent.com/29258390/28753012-6a73fa38-74e1-11e7-8054-55fe713fab51.PNG)

**Comment by saptarshibasu** [comment]
Fixed. Outer join issue in sql
