### ISSUE TITLE
Field titles are getting overwrite by field values in Employee Hierarchy Search in Problem with Version - IE 11 OS-Windows 10

### ISSUE THREAD

**Issue by debleena-123** [engineerscraft/hrms#17]
![image](https://user-images.githubusercontent.com/30408705/28753220-84ffbbae-754e-11e7-8bee-322eadf727bd.png)

**Comment by debleena-123** [comment]
![image](https://user-images.githubusercontent.com/30408705/28753237-faee247c-754e-11e7-886b-511aae98e095.png)

**Comment by saptarshibasu** [comment]
This is fixed now
