### ISSUE TITLE
Employee hierarchy search

### ISSUE THREAD

**Issue by lookatchandra** [engineerscraft/hrms#18]
After searching an employee we get the employee search result where there is a link on Employee Id.
Will it redirect to the employee detail after clicking on that link?

if so that's not redirecting to that page.

![log_emp_detail](https://user-images.githubusercontent.com/29258390/28753701-e98a5d52-74ec-11e7-8689-2f201ff28d63.PNG)

**Comment by saptarshibasu** [comment]
Please send the data of the employee that you have created

**Comment by saptarshibasu** [comment]
Fixed. SQL issue
