### ISSUE TITLE
Nominee details fields are not working in Emloyee creation additional detailes page

### ISSUE THREAD

**Issue by debleena-123** [engineerscraft/hrms#20]
overwrites are also getting  in additional details page of  IE   OS windows 10.               
![image](https://user-images.githubusercontent.com/30408705/28754069-fac504ea-755b-11e7-8988-7eae931cec8e.png)

**Comment by saptarshibasu** [comment]
Fixed. The span_1_of_4 is changed to span_4_of_4 in the htms
