### ISSUE TITLE
Employee Hierarchy search by Employee id

### ISSUE THREAD

**Issue by lookatchandra** [engineerscraft/hrms#22]
1.Create a new employee.
2.Search new employee by Employee Id in hierarchy search.

All employee data are coming in search result.
Another observation is designation is not showing here where if we search by organisation.
In employee search by employee id may be it is getting supervisor id(supervisor_id = :username) and hr id(hr_id = :username) in query as null string.
Query from log : 
SELECT DISTINCT empl.EMP_ID, empl.org_id, empl.unit_id, empl.department_id, empl.CONTACTNO, empl.EMPLOYEE_FIRST_NAME, empl.EMPLOYEE_MIDDLE_NAME, empl.EMPLOYEE_LAST_NAME, empl.EMAIL_ID, DEPARTMENT_NAME, DESIGNATION, SUP.EMAIL_ID SUPERVISOR_EMAIL_ID, HR.EMAIL_ID HR_EMAIL_ID  FROM ( SELECT A.EMP_ID, EMPLOYEE_FIRST_NAME, EMPLOYEE_MIDDLE_NAME, EMPLOYEE_LAST_NAME, a.org_id, a.unit_id, a.department_id, a.EMAIL_ID, HR_FLAG, SUPERVISOR_FLAG, NATIONALITY, SEX, MARITAL_STATUS, CONTACTNO, IDENTITY_DOC_TYPE_ID, IDENTITY_NUMBER, EMP_TYPE FROM HRMS.EMPLOYEE A WHERE A.EMP_ID IN (WITH RECURSIVE emp AS (SELECT emp_id, supervisor_id FROM HRMS.employee_hierarchy_status a WHERE supervisor_id = :username UNION ALL SELECT b.emp_id, b.supervisor_id FROM HRMS.employee_hierarchy_status b INNER JOIN emp c ON (b.supervisor_id = c.emp_id) ) SELECT emp_id FROM emp UNION ALL (WITH RECURSIVE emp AS (SELECT emp_id, supervisor_id FROM hrms.employee_hierarchy_status a WHERE hr_id = :username UNION ALL SELECT b.emp_id, b.supervisor_id FROM hrms.employee_hierarchy_status b INNER JOIN emp c ON (b.hr_id = c.emp_id) ) SELECT emp_id FROM emp) UNION ALL SELECT EMP_ID FROM HRMS.ROLE_DEPARTMENT A, HRMS.EMPLOYEE C WHERE ROLE_ID IN (SELECT ROLE_ID  FROM HRMS.ROLE_MASTER WHERE ROLE_NAME IN (:roleList)) AND A.DEPARTMENT_ID = C.DEPARTMENT_ID ) ) EMPL LEFT JOIN HRMS.EMPLOYEE_HIERARCHY_STATUS EHS ON EMPL.EMP_ID = EHS.EMP_ID  LEFT JOIN HRMS.EMPLOYEE SUP ON EHS.SUPERVISOR_ID = SUP.EMP_ID LEFT JOIN HRMS.EMPLOYEE HR ON EHS.HR_ID = HR.EMP_ID LEFT JOIN hrms.DEPARTMENT_MASTER DEPT ON EMPL.DEPARTMENT_ID = DEPT.DEPARTMENT_ID LEFT JOIN hrms.APPRAISAL_RATING AR ON EMPL.EMP_ID = AR.EMP_ID AND AR.APPRAISAL_ID = (SELECT APPRAISAL_ID FROM hrms.APPRAISAL_CYCLE WHERE ACTIVATION_DATE = (SELECT MAX(ACTIVATION_DATE) FROM hrms.APPRAISAL_CYCLE WHERE ACTIVATION_DATE<current_timestamp)) LEFT JOIN hrms.DESIGNATION_MASTER DESG ON AR.DESIGNATION_ID = DESG.DESIGNATION_ID  AND EMPL.EMP_ID = 'HUB000006' LIMIT 500
18:39:22,002 Params [ADMIN], TEST

The above query returns all the result with null string : 

sELECT DISTINCT empl.EMP_ID, empl.org_id, empl.unit_id, empl.department_id,
empl.CONTACTNO, empl.EMPLOYEE_FIRST_NAME, empl.EMPLOYEE_MIDDLE_NAME, empl.EMPLOYEE_LAST_NAME,
empl.EMAIL_ID, DEPARTMENT_NAME, DESIGNATION, SUP.EMAIL_ID SUPERVISOR_EMAIL_ID, HR.EMAIL_ID HR_EMAIL_ID 
FROM ( SELECT A.EMP_ID, EMPLOYEE_FIRST_NAME, EMPLOYEE_MIDDLE_NAME, EMPLOYEE_LAST_NAME, a.org_id,
      a.unit_id, a.department_id, a.EMAIL_ID, HR_FLAG, SUPERVISOR_FLAG, NATIONALITY, SEX, MARITAL_STATUS, CONTACTNO,
      IDENTITY_DOC_TYPE_ID, IDENTITY_NUMBER, EMP_TYPE FROM HRMS.EMPLOYEE A WHERE A.EMP_ID IN (WITH RECURSIVE emp
      AS (SELECT emp_id, supervisor_id FROM HRMS.employee_hierarchy_status a WHERE supervisor_id = '' 
      UNION ALL SELECT b.emp_id, b.supervisor_id FROM HRMS.employee_hierarchy_status b INNER JOIN emp c
    ON (b.supervisor_id = c.emp_id) ) SELECT emp_id FROM emp UNION ALL 
   (WITH RECURSIVE emp AS (SELECT emp_id, supervisor_id FROM hrms.employee_hierarchy_status a 
   WHERE hr_id = '' UNION ALL SELECT b.emp_id, b.supervisor_id FROM hrms.employee_hierarchy_status b
  INNER JOIN emp c ON (b.hr_id = c.emp_id) ) SELECT emp_id FROM emp) UNION ALL SELECT EMP_ID 
   FROM HRMS.ROLE_DEPARTMENT A, HRMS.EMPLOYEE C WHERE ROLE_ID IN (SELECT ROLE_ID  
   FROM HRMS.ROLE_MASTER WHERE ROLE_NAME IN ('ADMIN')) AND A.DEPARTMENT_ID = C.DEPARTMENT_ID ) ) EMPL
   LEFT JOIN HRMS.EMPLOYEE_HIERARCHY_STATUS EHS ON EMPL.EMP_ID = EHS.EMP_ID  LEFT JOIN HRMS.EMPLOYEE SUP
   ON EHS.SUPERVISOR_ID = SUP.EMP_ID LEFT JOIN HRMS.EMPLOYEE HR ON EHS.HR_ID = HR.EMP_ID LEFT JOIN
   hrms.DEPARTMENT_MASTER DEPT ON EMPL.DEPARTMENT_ID = DEPT.DEPARTMENT_ID LEFT JOIN hrms.APPRAISAL_RATING AR
   ON EMPL.EMP_ID = AR.EMP_ID AND AR.APPRAISAL_ID = (SELECT APPRAISAL_ID FROM hrms.APPRAISAL_CYCLE WHERE 
   ACTIVATION_DATE = (SELECT MAX(ACTIVATION_DATE) FROM hrms.APPRAISAL_CYCLE WHERE 
   ACTIVATION_DATE<current_timestamp)) LEFT JOIN hrms.DESIGNATION_MASTER DESG ON 
   AR.DESIGNATION_ID = DESG.DESIGNATION_ID  AND
EMPL.EMP_ID = 'HUB000006' LIMIT 500;

Also the link in the employee search result is not working.

Screen shots are attached : 

![emp_hierarchy_search_by_emp_id](https://user-images.githubusercontent.com/29258390/28827595-f1f7c852-7682-11e7-8ab2-1a2d85e8485a.PNG)

![log_search_by_emp_id](https://user-images.githubusercontent.com/29258390/28827624-02df52d4-7683-11e7-8b87-72b4c4389ce0.PNG)

![org_info_search](https://user-images.githubusercontent.com/29258390/28827649-18fbf4e6-7683-11e7-9459-5d81a578ceea.PNG)

![log_search_by_org](https://user-images.githubusercontent.com/29258390/28827675-272aabb6-7683-11e7-8561-1fe38ddb9894.PNG)

![search_result_by_emp_id](https://user-images.githubusercontent.com/29258390/28827704-3fe4d0e6-7683-11e7-8748-99b77e9f0862.PNG)

**Comment by saptarshibasu** [comment]
DB was refreshed and this is fixed
