### ISSUE TITLE
Employee creation error

### ISSUE THREAD

**Issue by lookatchandra** [engineerscraft/hrms#23]
1.Refreshed the database
2.During employee creation getting error 'ERR_250_ENTRY_ALREADY_EXISTS' though there are no employee in with employee id =HUB000002.
3.No specific message is shown in GUI, the error which we got from the code is showing here.

[hrms_log_Err.txt](https://github.com/engineerscraft/hrms/files/1191134/hrms_log_Err.txt)

![emp_creation_err_01082017](https://user-images.githubusercontent.com/29258390/28833884-8f9bb85e-7695-11e7-8b3e-ca389b5e80bb.PNG)

**Comment by iamjyotirmoy** [comment]
This is an error from the LDAP. Please check in your LDAP, the previously created employee records are still there, and that is causing the issue!

**Comment by saptarshibasu** [comment]
Closed as it's just a unique key violation in LDAP. LDAP data is not refreshed and DB is refreshed
