### ISSUE TITLE
Employee Creation

### ISSUE THREAD

**Issue by lookatchandra** [engineerscraft/hrms#6]
No data found in Employee creation page of the following drop down : Nationality,Organization,Unit,Identity Doc Type.
Screenshots are attached.

Is it required to have back button to go to the home `page.

![db_unit](https://user-images.githubusercontent.com/29258390/28666888-177fc8c6-727e-11e7-9111-e9980cabb5ba.PNG)
![err_emp_creation](https://user-images.githubusercontent.com/29258390/28666890-178503e0-727e-11e7-810e-b37610831131.PNG)
![db_org](https://user-images.githubusercontent.com/29258390/28666889-1782e1fa-727e-11e7-9e6f-7ce491e04138.PNG)

`

**Comment by saptarshibasu** [comment]
Fixed. The problem was in SQL

**Comment by saptarshibasu** [comment]
This is working with the code in the new repository. Please close.

**Comment by lookatchandra** [comment]
Invalid
