### ISSUE TITLE
New employee creation Issue

### ISSUE THREAD

**Issue by lookatchandra** [engineerscraft/hrms#7]
Getting error during Employee creation.
Actual error message is not shown.

![new_emp_creation](https://user-images.githubusercontent.com/29258390/28668353-23c28e74-7284-11e7-9f39-5974685dc7ac.PNG)

[Employee_table.txt](https://github.com/engineerscraft/hrms/files/1185838/Employee_table.txt)

**Comment by lookatchandra** [comment]
![emp_create_log](https://user-images.githubusercontent.com/29258390/28673960-d74660e2-7298-11e7-8c46-2b12e87fa20d.PNG)

![emp_string_err](https://user-images.githubusercontent.com/29258390/28675792-c25c6708-729d-11e7-8310-32110d89e307.PNG)


Number format exception in EmployeeAddress 👍 

INSERT INTO HRMS.ADDRESS (EMP_ID, ADDRESS_TYPE,  HOUSE_NO, STREET_NAME, AREA, RE
GION, PIN_NO, DISTRICT_ID, STATE_ID, COUNTRY_ID, DESCRIPTION) VALUES (?,?,?,?,?,
?,?,?,?,?,?)
Params HUB000002, permanent, , , , , , 0, 0, 0, null
For input string: ""
java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(NumberFormatException.
java:65) ~[?:1.8.0_131]
        at java.lang.Integer.parseInt(Integer.java:592) ~[?:1.8.0_131]
        at java.lang.Integer.valueOf(Integer.java:766) ~[?:1.8.0_131]
        at com.hamdard.hua.repository.EmployeeRepository.insertEmployeeAddress(E
mployeeRepository.java:262) ~[classes/:?]
        at com.hamdard.hua.repository.EmployeeRepository.createEmployee(Employee
Repository.java:165) ~[classes/:?]
        at com.hamdard.hua.repository.EmployeeRepository$$FastClassBySpringCGLIB
$$16279f0a.invoke(<generated>) ~[classes/:?]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:2
04) ~[spring-core-4.3.5.RELEASE.jar:4.3.5.RELEASE]

**Comment by iamjyotirmoy** [comment]
Will be corrected once validations are in place

**Comment by iamjyotirmoy** [comment]
Fixed!

**Comment by iSomdeb** [comment]
@saptarshibasu, I was mentioning about this modal dialog in the employee creation for the backdrop.

**Comment by lookatchandra** [comment]
In employee creation after creating the new  employee the page is not getting refreshed and with the same information multiple employees can be created.
Also during creation of new employee current date is not highlighted/selected in the date picker in date of joining.

![emp_creation_personal_dtl](https://user-images.githubusercontent.com/29258390/28752648-88b6d5ea-74d9-11e7-9cfc-28327c6c78e3.PNG)

![current_date_highlight](https://user-images.githubusercontent.com/29258390/28752652-9ccc434e-74d9-11e7-9040-526f38d9eff5.PNG)


![db_emp_name_debjyoti](https://user-images.githubusercontent.com/29258390/28752655-aac5f33c-74d9-11e7-9a72-272c8bf73ee3.PNG)

**Comment by saptarshibasu** [comment]
Fixed. Performance part we will see later once the functionalities are all ready. It is difficult to evaluate the performance now as the servers are all running in dev mode
