### ISSUE TITLE
Employee hierarchy search by Organization

### ISSUE THREAD

**Issue by lookatchandra** [engineerscraft/hrms#8]
No data is retrieving in Employee hierarchy search by Organisation.

![org_info_search](https://user-images.githubusercontent.com/29258390/28668727-24299e96-7286-11e7-82cd-d6780cadc7ae.PNG)

**Comment by saptarshibasu** [comment]
Fixed the SQL

**Comment by lookatchandra** [comment]
its working now.....thanks
